import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { LaundryService } from "@/models/Service";
const defaults = [
  {name:"Regular Wash",icon:"🧺",color:"blue",items:[{name:"Shirt / T-shirt",icon:"👕",price:35},{name:"Trouser / Jeans",icon:"👖",price:45},{name:"Kurta / Top",icon:"🥼",price:40},{name:"Saree",icon:"🥻",price:70},{name:"Bedsheet",icon:"🛏️",price:80},{name:"Towel",icon:"🧻",price:30}]},
  {name:"Dry Cleaning",icon:"🤵",color:"violet",items:[{name:"Blazer",icon:"🧥",price:220},{name:"2-Piece Suit",icon:"🤵",price:450},{name:"Silk Saree",icon:"🥻",price:280},{name:"Evening Gown",icon:"👗",price:350},{name:"Winter Coat",icon:"🧥",price:320},{name:"Silk Shirt",icon:"👔",price:160}]},
  {name:"Ironing",icon:"♨️",color:"mint",items:[{name:"Shirt / T-shirt",icon:"👕",price:15},{name:"Trouser / Jeans",icon:"👖",price:20},{name:"Kurta / Top",icon:"🥼",price:20},{name:"Saree",icon:"🥻",price:45},{name:"Bedsheet",icon:"🛏️",price:35},{name:"Dress",icon:"👗",price:35}]},
  {name:"Comforters",icon:"🛏️",color:"sand",items:[{name:"Single Comforter",icon:"🛏️",price:220},{name:"Double Comforter",icon:"🛏️",price:320},{name:"King Comforter",icon:"🛏️",price:420},{name:"Duvet",icon:"🧺",price:280}]},
  {name:"Curtains",icon:"🪟",color:"rose",items:[{name:"Window Curtain",icon:"🪟",price:100},{name:"Door Curtain",icon:"🪟",price:150},{name:"Sheer Curtain",icon:"🪟",price:90},{name:"Blackout Curtain",icon:"🪟",price:190}]},
  {name:"Shoes",icon:"👟",color:"cyan",items:[{name:"Sneakers",icon:"👟",price:220},{name:"Formal Shoes",icon:"👞",price:240},{name:"Sports Shoes",icon:"👟",price:260},{name:"Boots",icon:"🥾",price:320},{name:"Sandals",icon:"🩴",price:160}]},
  {name:"Women’s Dry Cleaning",icon:"👗",color:"pink",items:[{name:"Saree",icon:"🥻",price:220},{name:"Dress",icon:"👗",price:200},{name:"Gown",icon:"👗",price:350},{name:"Lehenga",icon:"🥻",price:480},{name:"Blouse",icon:"👚",price:120},{name:"Women’s Jacket",icon:"🧥",price:220}]},
  {name:"Men’s Dry Cleaning",icon:"👔",color:"sky",items:[{name:"Blazer",icon:"🧥",price:220},{name:"2-Piece Suit",icon:"🤵",price:450},{name:"Formal Shirt",icon:"👔",price:140},{name:"Formal Trouser",icon:"👖",price:160},{name:"Kurta",icon:"🥼",price:170},{name:"Sherwani",icon:"🤵",price:500}]},
  {name:"Blankets",icon:"🧶",color:"lilac",items:[{name:"Single Blanket",icon:"🧶",price:150},{name:"Double Blanket",icon:"🧶",price:220},{name:"King Blanket",icon:"🧶",price:300},{name:"Woollen Blanket",icon:"🧶",price:260},{name:"Baby Blanket",icon:"🧶",price:100}]},
];
export async function GET(){try{await connectDB();if(await LaundryService.countDocuments()===0)await LaundryService.insertMany(defaults);return NextResponse.json(await LaundryService.find().sort({createdAt:1}).lean())}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to load services"},{status:503})}}
export async function POST(request:Request){try{const body=await request.json();if(!body.name?.trim()||!Array.isArray(body.items)||!body.items.length)return NextResponse.json({error:"Service name and items are required"},{status:400});await connectDB();const service=await LaundryService.create({name:body.name,icon:body.icon,color:body.color,price:body.price||0,items:body.items});return NextResponse.json(service,{status:201})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Unable to create service"},{status:500})}}
